spring.application.name=spring-boot-admin

server.port=9090

# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator del propio Spring Boot Admin
management.endpoints.web.exposure.include=health,info,metrics,env,beans,loggers,threaddump,httpexchanges
management.endpoint.health.show-details=always
management.info.env.enabled=true

# Info visible
info.app.name=Spring Boot Admin
info.app.description=Servidor de monitoreo de microservicios Innovatech
info.app.version=1.0.0