FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY businessdomain ./businessdomain
COPY infraestructuredomain ./infraestructuredomain

ARG MODULE_PATH

RUN mvn -pl ${MODULE_PATH} -am clean package -DskipTests

RUN mkdir -p /app/output && cp ${MODULE_PATH}/target/*.jar /app/output/app.jar

FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/output/app.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]