spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.enable-self-preservation=false

management.endpoints.web.exposure.include=health,info,metrics,env,beans,loggers,threaddump,httpexchanges
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.description=Microservicio de la plataforma Innovatech
info.app.version=1.0.0