spring.application.name=api-gateway

server.port=8090

# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# API GATEWAY ROUTES
# ===============================

# proyectos-service
spring.cloud.gateway.server.webmvc.routes[0].id=proyectos-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/proyectos/**

# equipos-service
spring.cloud.gateway.server.webmvc.routes[1].id=equipos-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/equipos/**

# tareas-service
spring.cloud.gateway.server.webmvc.routes[2].id=tareas-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/tareas/**

# bff-service
spring.cloud.gateway.server.webmvc.routes[3].id=bff-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/bff/**